version: '3.8'
services:
  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  # backend:
  #   build: 
  #     context: ./Backend
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - "4000:4000"